cicd
pkgxdev/ossapp pull request #800
Opened 2023-10-03 02:05 UTC by getneil

2023-10-03 12:54 UTC, mxcl commented on .github/workflows/ci.yml
>            export version=$(echo $(cat package.json) | jq --raw-output .version)
could avoid line 115 and just do `pkgx jq --raw…` here

2023-10-03 12:55 UTC, mxcl commented on .github/workflows/release.yml
> +            s3://preview.gui.tea.xyz/release/ossapp-previous-arm64.dmg
put the bucket id in a secret

2023-10-03 12:55 UTC, mxcl requested changes
almost

2023-10-04 10:45 UTC, getneil commented on .github/workflows/release.yml
> +            s3://preview.gui.tea.xyz/release/ossapp-previous-arm64.dmg
applied all of this.

2023-10-04 11:11 UTC, mxcl approved these changes

2023-10-04 11:11 UTC, merged