Add Dutch (Nederlands)
pkgxdev/ossapp pull request #854
Opened 2024-01-18 13:31 UTC by evaeth

Add Dutch language

2024-01-18 13:34 UTC, DavidKorystov requested changes

2024-01-18 13:34 UTC, DavidKorystov commented on svelte/src/libs/translations/index.ts
> +import lt from "./languages/nl.json";
```suggestion
import nl from "./languages/nl.json";
```

2024-01-18 13:37 UTC, evaeth commented on svelte/src/libs/translations/index.ts
> +import lt from "./languages/nl.json";
Done!

2024-01-18 14:20 UTC, DavidKorystov approved these changes

2024-01-18 14:46 UTC, evaeth commented on svelte/src/libs/translations/index.ts
> +import lt from "./languages/nl.json";
Can this PR be merged?

2024-01-19 02:10 UTC, getneil commented
@DavidKorystov please fix conflicts thanks

2024-01-19 02:10 UTC, getneil commented
@evaeth please fix conflicts thanks

2024-01-19 08:15 UTC, evaeth commented
> @evaeth please fix conflicts thanks

Fixed

2024-01-19 12:52 UTC, evaeth commented
@getneil are there any other issues?

2024-01-21 02:36 UTC, getneil commented
@evaeth  please fix conflict again. sorry as i merge other prs from other contributors i just approve/merge those that addresses their issue the earliest.

2024-01-21 14:26 UTC, evaeth commented
@getneil No problem. Fixed

2024-01-22 19:35 UTC, evaeth commented
@getneil any other issues?

2024-01-23 03:08 UTC, getneil commented
@evaeth did not pass the lint. executing `xc format` would automatically do it.

2024-01-23 11:36 UTC, evaeth commented
@getneil any advice how to fix it?

2024-01-23 17:30 UTC, evaeth commented
@getneil now it should pass

2024-01-25 13:11 UTC, evaeth commented
@getneil one more try

2024-01-27 22:20 UTC, evaeth commented
@getneil could you please check it

2024-01-28 13:06 UTC, merged